### ISSUE TITLE
spelling directive doesn't work with parallel builds

### ISSUE THREAD

**Issue by webknjaz** [sphinx-contrib/spelling#34] opened 2019-10-29 20:29 UTC
So I've tried adding a spelling directive with a list of words to the top of one RST file and it doesn't seem to work at all.
Any ideas on where do I start debugging?

I've looked into the source code and it seems it should do some logging but I don't see anything in the console output...

**Comment by webknjaz** [comment] 2019-10-29 20:39
I re-ran it with `-vv` and now see:
```console
Extending local dictionary for pkg/cheroot.test with ['webtest']
```
in the output which means that Sphinx actually runs the directive code.

But for some reason, `sphinxcontrib-spelling` doesn't ignore that word ("webtest") when it's declared by the directive.
It does ignore it when it's added to the global word list in a separate file, though.

**Comment by dhellmann** [comment] 2019-11-04 22:04
Is your documentation set public? I could download it and experiment.

In the mean time, the directive is meant to be used to configure the local dictionary for the document in which the directive appears. The entries added by the directive do not apply to other documents.

**Comment by webknjaz** [comment] 2019-11-04 22:07
https://github.com/cherrypy/cheroot
Build with `tox -e build-docs`.

Yes, I understand that the directive is supposed to affect only the document where it's added.

**Comment by dhellmann** [comment] 2019-11-05 16:51
I can reproduce the problem, but I don't understand it, yet. I added extra logging to the extension and I can see that the dictionary in the environment with the document-specific filters is being extended and then the same dictionary is empty when it comes time to actually check the document. It has the same python ID, so I don't think the object is being recreated. I'll need to spend more time debugging to understand what's going on.

**Comment by dhellmann** [comment] 2019-11-05 22:04
The issue is the use of parallel builds via the -j option to Sphinx. The directive is trying to modify builder state as it reads files, but that state is modified in a worker process and not made available in the builder process. I imagine there is a way to store the state so the builder can see it, but until I figure out how to do that you could remove the '-j auto' from the command line in your tox.ini for the spelling check build.

**Comment by webknjaz** [comment] 2019-11-05 23:28
Wow, that's surprising! Thanks for the hint! I'll keep this in mind.

**Comment by jdillard** [comment] 2020-06-19 22:38
If the extension doesn't support parallel builds, should `parallel_read_safe` be marked as `False` instead of `True`?

https://github.com/sphinx-contrib/spelling/blob/9c2a0e76535b2fb11be1a141dfaca09363886a9e/sphinxcontrib/spelling/__init__.py#L46

**Comment by dhellmann** [comment] 2020-06-21 13:32
> If the extension doesn't support parallel builds, should `parallel_read_safe` be marked as `False` instead of `True`?
> 
> https://github.com/sphinx-contrib/spelling/blob/9c2a0e76535b2fb11be1a141dfaca09363886a9e/sphinxcontrib/spelling/__init__.py#L46

Apparently so. I'm not sure if parallel builds used to work and stopped at some point or if it never worked at all.

**Comment by jdillard** [comment] 2020-06-22 01:58
I just opened PR #54 to mark `parallel_read_safe` as `False`. I'm not sure if you want to turn this issue into an "enhancement" placeholder for adding support for parallel builds.

**Comment by webknjaz** [comment] 2020-07-26 18:50
Ref #59

**Closed** 2020-07-28 20:10 UTC
Labels: bug
